### ISSUE TITLE
update links on student page

### ISSUE THREAD

**Issue by andrewringler** [evaloh728/web1-f16-student#2]
Eva,

This links to your assignments that are on your [student page](https://evaloh728.github.io/web1-f16-student/) are not working. It looks like you copy-pasted the URLs in the address bar. Those URLs are specific to your computer, they don't work here.

For example the assignment 2 link should be:
<a href="Assignment%202/HW2-HanabiMatsuri.html">Assignment 2</a>: Event Promotion</li>

In general please make sure to preview all of your web pages online from your student page. Not just locally.

Thanks,

Andrew

**Comment by andrewringler** [comment]
Same issue with Assignment 3.

Take a look at https://evaloh728.github.io/web1-f16-student/Assignment%203/homepage.html online. None of the links work.

Thanks,

Andrew

**Comment by evaloh728** [comment]
updated

**Comment by andrewringler** [comment]
Please take a look at your link to assignment #3 from your student page:
https://evaloh728.github.io/web1-f16-student/

It is not working.

Andrew
